[2025-04-03T02:06:36.423+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline_dag.download_data_parquet manual__2025-04-03T02:06:29.414785+00:00 [queued]>
[2025-04-03T02:06:36.469+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline_dag.download_data_parquet manual__2025-04-03T02:06:29.414785+00:00 [queued]>
[2025-04-03T02:06:36.470+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-04-03T02:06:36.601+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_data_parquet> on 2025-04-03 02:06:29.414785+00:00
[2025-04-03T02:06:36.617+0000] {standard_task_runner.py:60} INFO - Started process 129 to run task
[2025-04-03T02:06:36.623+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline_dag', 'download_data_parquet', 'manual__2025-04-03T02:06:29.414785+00:00', '--job-id', '88', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmpcnukqqny']
[2025-04-03T02:06:36.627+0000] {standard_task_runner.py:88} INFO - Job 88: Subtask download_data_parquet
[2025-04-03T02:06:36.759+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-03T02:06:36.951+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipeline_dag.download_data_parquet manual__2025-04-03T02:06:29.414785+00:00 [running]> on host c604bbf95a3a
[2025-04-03T02:06:37.447+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='full_pipeline_dag' AIRFLOW_CTX_TASK_ID='download_data_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-04-03T02:06:29.414785+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-03T02:06:29.414785+00:00'
[2025-04-03T02:06:37.571+0000] {logging_mixin.py:188} INFO - ðŸ“¥ Downloading CSV...
[2025-04-03T02:06:49.272+0000] {logging_mixin.py:188} INFO - âœ… Download complete!
[2025-04-03T02:06:49.274+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_pipeline_dag.py", line 29, in download_data
    from ingest.download_parquet import main as download_main
ImportError: cannot import name 'main' from 'ingest.download_parquet' (/opt/pipeline/ingest/download_parquet.py)
[2025-04-03T02:06:49.334+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=full_pipeline_dag, task_id=download_data_parquet, execution_date=20250403T020629, start_date=20250403T020636, end_date=20250403T020649
[2025-04-03T02:06:49.488+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 88 for task download_data_parquet (cannot import name 'main' from 'ingest.download_parquet' (/opt/pipeline/ingest/download_parquet.py); 129)
[2025-04-03T02:06:49.533+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-03T02:06:49.629+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
