[2025-04-02T19:02:42.821+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline_dag.download_data_parquet manual__2025-04-02T19:01:05.542401+00:00 [queued]>
[2025-04-02T19:02:42.842+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline_dag.download_data_parquet manual__2025-04-02T19:01:05.542401+00:00 [queued]>
[2025-04-02T19:02:42.842+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-04-02T19:02:42.915+0000] {taskinstance.py:2191} INFO - Executing <Task(PythonOperator): download_data_parquet> on 2025-04-02 19:01:05.542401+00:00
[2025-04-02T19:02:42.920+0000] {standard_task_runner.py:60} INFO - Started process 78 to run task
[2025-04-02T19:02:42.924+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline_dag', 'download_data_parquet', 'manual__2025-04-02T19:01:05.542401+00:00', '--job-id', '78', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmp1ji_3t8t']
[2025-04-02T19:02:42.925+0000] {standard_task_runner.py:88} INFO - Job 78: Subtask download_data_parquet
[2025-04-02T19:02:42.972+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-02T19:02:43.045+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipeline_dag.download_data_parquet manual__2025-04-02T19:01:05.542401+00:00 [running]> on host a210a0004273
[2025-04-02T19:02:43.230+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='full_pipeline_dag' AIRFLOW_CTX_TASK_ID='download_data_parquet' AIRFLOW_CTX_EXECUTION_DATE='2025-04-02T19:01:05.542401+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-02T19:01:05.542401+00:00'
[2025-04-02T19:02:43.290+0000] {logging_mixin.py:188} INFO - ðŸ“¥ Downloading CSV...
[2025-04-02T19:03:10.866+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 199, in execute
    return_value = self.execute_callable()
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/python.py", line 216, in execute_callable
    return self.python_callable(*self.op_args, **self.op_kwargs)
  File "/opt/airflow/dags/full_pipeline_dag.py", line 29, in download_data
    from ingest.download_parquet import main as download_main
  File "/opt/pipeline/ingest/download_parquet.py", line 8, in <module>
    with open(output, "wb") as f:
FileNotFoundError: [Errno 2] No such file or directory: 'data/raw/yellow_tripdata_2023-01.parquet'
[2025-04-02T19:03:10.909+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=full_pipeline_dag, task_id=download_data_parquet, execution_date=20250402T190105, start_date=20250402T190242, end_date=20250402T190310
[2025-04-02T19:03:10.962+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 78 for task download_data_parquet ([Errno 2] No such file or directory: 'data/raw/yellow_tripdata_2023-01.parquet'; 78)
[2025-04-02T19:03:10.982+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-02T19:03:11.016+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
