[2025-04-04T08:45:02.234+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline_dag.load_to_postgres manual__2025-04-04T08:16:15.521213+00:00 [queued]>
[2025-04-04T08:45:02.254+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline_dag.load_to_postgres manual__2025-04-04T08:16:15.521213+00:00 [queued]>
[2025-04-04T08:45:02.255+0000] {taskinstance.py:2170} INFO - Starting attempt 1 of 3
[2025-04-04T08:45:02.290+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_to_postgres> on 2025-04-04 08:16:15.521213+00:00
[2025-04-04T08:45:02.295+0000] {standard_task_runner.py:60} INFO - Started process 1361 to run task
[2025-04-04T08:45:02.298+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline_dag', 'load_to_postgres', 'manual__2025-04-04T08:16:15.521213+00:00', '--job-id', '276', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmplc4msj95']
[2025-04-04T08:45:02.299+0000] {standard_task_runner.py:88} INFO - Job 276: Subtask load_to_postgres
[2025-04-04T08:45:02.338+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T08:45:02.389+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipeline_dag.load_to_postgres manual__2025-04-04T08:16:15.521213+00:00 [running]> on host 43987fe3142a
[2025-04-04T08:45:02.553+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='full_pipeline_dag' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T08:16:15.521213+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T08:16:15.521213+00:00'
[2025-04-04T08:45:02.555+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-04T08:45:02.557+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        /opt/spark/bin/spark-submit         --master spark://spark-master:7077         /opt/spark-app/load_to_postgres.py\n        ']
[2025-04-04T08:45:02.571+0000] {subprocess.py:86} INFO - Output:
[2025-04-04T08:45:02.578+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-04T08:45:05.181+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SparkContext: Running Spark version 3.5.0
[2025-04-04T08:45:05.182+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-04-04T08:45:05.183+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SparkContext: Java version 17.0.14
[2025-04-04T08:45:05.221+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-04T08:45:05.297+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO ResourceUtils: ==============================================================
[2025-04-04T08:45:05.298+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-04-04T08:45:05.298+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO ResourceUtils: ==============================================================
[2025-04-04T08:45:05.298+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SparkContext: Submitted application: LoadCleanedToPostgres
[2025-04-04T08:45:05.314+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-04-04T08:45:05.321+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO ResourceProfile: Limiting resource is cpu
[2025-04-04T08:45:05.322+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-04-04T08:45:05.357+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SecurityManager: Changing view acls to: airflow
[2025-04-04T08:45:05.357+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SecurityManager: Changing modify acls to: airflow
[2025-04-04T08:45:05.358+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SecurityManager: Changing view acls groups to:
[2025-04-04T08:45:05.359+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SecurityManager: Changing modify acls groups to:
[2025-04-04T08:45:05.360+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: airflow; groups with view permissions: EMPTY; users with modify permissions: airflow; groups with modify permissions: EMPTY
[2025-04-04T08:45:05.565+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO Utils: Successfully started service 'sparkDriver' on port 34371.
[2025-04-04T08:45:05.591+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SparkEnv: Registering MapOutputTracker
[2025-04-04T08:45:05.623+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SparkEnv: Registering BlockManagerMaster
[2025-04-04T08:45:05.637+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-04-04T08:45:05.638+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-04-04T08:45:05.641+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-04-04T08:45:05.658+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-c1e0d786-f8ce-4d19-a984-6b71d916d957
[2025-04-04T08:45:05.674+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-04-04T08:45:05.690+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-04-04T08:45:05.789+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-04-04T08:45:05.852+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-04-04T08:45:05.955+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-04-04T08:45:05.994+0000] {subprocess.py:93} INFO - 25/04/04 08:45:05 INFO TransportClientFactory: Successfully created connection to spark-master/172.24.0.4:7077 after 21 ms (0 ms spent in bootstraps)
[2025-04-04T08:45:06.070+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250404084506-0005
[2025-04-04T08:45:06.076+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250404084506-0005/0 on worker-20250404081326-172.24.0.8-45963 (172.24.0.8:45963) with 2 core(s)
[2025-04-04T08:45:06.080+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO StandaloneSchedulerBackend: Granted executor ID app-20250404084506-0005/0 on hostPort 172.24.0.8:45963 with 2 core(s), 1024.0 MiB RAM
[2025-04-04T08:45:06.082+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 37393.
[2025-04-04T08:45:06.084+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO NettyBlockTransferService: Server created on 43987fe3142a:37393
[2025-04-04T08:45:06.085+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-04-04T08:45:06.090+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 43987fe3142a, 37393, None)
[2025-04-04T08:45:06.092+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO BlockManagerMasterEndpoint: Registering block manager 43987fe3142a:37393 with 434.4 MiB RAM, BlockManagerId(driver, 43987fe3142a, 37393, None)
[2025-04-04T08:45:06.094+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 43987fe3142a, 37393, None)
[2025-04-04T08:45:06.096+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 43987fe3142a, 37393, None)
[2025-04-04T08:45:06.170+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250404084506-0005/0 is now RUNNING
[2025-04-04T08:45:06.324+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-04-04T08:45:06.512+0000] {subprocess.py:93} INFO - ðŸš€ SparkSession ready!
[2025-04-04T08:45:06.513+0000] {subprocess.py:93} INFO - ðŸ“¥ Loading cleaned data from MinIO...
[2025-04-04T08:45:06.571+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-04-04T08:45:06.578+0000] {subprocess.py:93} INFO - 25/04/04 08:45:06 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmp7lnk_x3c/spark-warehouse'.
[2025-04-04T08:45:07.303+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi/clean/yellow_tripdata_2023-01-clean.parquet.
[2025-04-04T08:45:07.304+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-04-04T08:45:07.304+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-04-04T08:45:07.305+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-04-04T08:45:07.306+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-04-04T08:45:07.306+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-04-04T08:45:07.307+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-04-04T08:45:07.308+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-04-04T08:45:07.308+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-04-04T08:45:07.309+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-04-04T08:45:07.309+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2025-04-04T08:45:07.310+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
[2025-04-04T08:45:07.311+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-04-04T08:45:07.311+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-04-04T08:45:07.311+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-04-04T08:45:07.312+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-04-04T08:45:07.312+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:563)
[2025-04-04T08:45:07.313+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-04-04T08:45:07.313+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-04-04T08:45:07.314+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-04-04T08:45:07.314+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-04-04T08:45:07.315+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-04-04T08:45:07.315+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-04-04T08:45:07.316+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-04-04T08:45:07.316+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-04-04T08:45:07.317+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-04-04T08:45:07.317+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-04-04T08:45:07.318+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-04-04T08:45:07.318+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-04T08:45:07.318+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-04-04T08:45:07.319+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-04-04T08:45:07.319+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-04-04T08:45:07.320+0000] {subprocess.py:93} INFO - 	... 26 more
[2025-04-04T08:45:07.390+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-04T08:45:07.392+0000] {subprocess.py:93} INFO -   File "/opt/spark-app/load_to_postgres.py", line 20, in <module>
[2025-04-04T08:45:07.395+0000] {subprocess.py:93} INFO -     df = spark.read.parquet(clean_path)
[2025-04-04T08:45:07.395+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
[2025-04-04T08:45:07.396+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-04-04T08:45:07.396+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-04-04T08:45:07.397+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-04-04T08:45:07.398+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o38.parquet.
[2025-04-04T08:45:07.398+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-04-04T08:45:07.399+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-04-04T08:45:07.399+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-04-04T08:45:07.400+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-04-04T08:45:07.400+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-04-04T08:45:07.401+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-04-04T08:45:07.401+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-04-04T08:45:07.402+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-04-04T08:45:07.403+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-04-04T08:45:07.403+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:724)
[2025-04-04T08:45:07.404+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-04-04T08:45:07.404+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:722)
[2025-04-04T08:45:07.405+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:551)
[2025-04-04T08:45:07.405+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:404)
[2025-04-04T08:45:07.406+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-04-04T08:45:07.406+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-04-04T08:45:07.406+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-04-04T08:45:07.407+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-04-04T08:45:07.408+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:563)
[2025-04-04T08:45:07.408+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-04-04T08:45:07.409+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-04-04T08:45:07.409+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-04-04T08:45:07.410+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-04-04T08:45:07.410+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-04-04T08:45:07.411+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-04-04T08:45:07.411+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-04-04T08:45:07.412+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-04-04T08:45:07.412+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-04-04T08:45:07.413+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-04-04T08:45:07.413+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-04-04T08:45:07.414+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-04T08:45:07.414+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-04-04T08:45:07.415+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-04-04T08:45:07.415+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-04-04T08:45:07.416+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-04-04T08:45:07.416+0000] {subprocess.py:93} INFO - 
[2025-04-04T08:45:07.467+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO SparkContext: Invoking stop() from shutdown hook
[2025-04-04T08:45:07.468+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-04-04T08:45:07.483+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO SparkUI: Stopped Spark web UI at http://43987fe3142a:4040
[2025-04-04T08:45:07.488+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-04-04T08:45:07.492+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-04-04T08:45:07.509+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-04-04T08:45:07.527+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO MemoryStore: MemoryStore cleared
[2025-04-04T08:45:07.528+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO BlockManager: BlockManager stopped
[2025-04-04T08:45:07.534+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-04-04T08:45:07.538+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-04-04T08:45:07.555+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO SparkContext: Successfully stopped SparkContext
[2025-04-04T08:45:07.556+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO ShutdownHookManager: Shutdown hook called
[2025-04-04T08:45:07.556+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-641ec2ab-8267-463a-81bd-7da1449f9a9b
[2025-04-04T08:45:07.568+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-177328a5-e1ac-44ba-ac58-d3f4b2fd524c
[2025-04-04T08:45:07.576+0000] {subprocess.py:93} INFO - 25/04/04 08:45:07 INFO ShutdownHookManager: Deleting directory /tmp/spark-177328a5-e1ac-44ba-ac58-d3f4b2fd524c/pyspark-e0a89e73-a6bf-467c-a487-a51af3cd80dd
[2025-04-04T08:45:07.619+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-04T08:45:07.645+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-04T08:45:07.651+0000] {taskinstance.py:1138} INFO - Marking task as UP_FOR_RETRY. dag_id=full_pipeline_dag, task_id=load_to_postgres, execution_date=20250404T081615, start_date=20250404T084502, end_date=20250404T084507
[2025-04-04T08:45:07.718+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 276 for task load_to_postgres (Bash command failed. The command returned a non-zero exit code 1.; 1361)
[2025-04-04T08:45:07.763+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-04T08:45:07.803+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
