[2025-04-04T08:46:10.627+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: full_pipeline_dag.load_to_postgres manual__2025-04-04T08:16:15.521213+00:00 [queued]>
[2025-04-04T08:46:10.642+0000] {taskinstance.py:1956} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: full_pipeline_dag.load_to_postgres manual__2025-04-04T08:16:15.521213+00:00 [queued]>
[2025-04-04T08:46:10.642+0000] {taskinstance.py:2170} INFO - Starting attempt 2 of 3
[2025-04-04T08:46:10.674+0000] {taskinstance.py:2191} INFO - Executing <Task(BashOperator): load_to_postgres> on 2025-04-04 08:16:15.521213+00:00
[2025-04-04T08:46:10.678+0000] {standard_task_runner.py:60} INFO - Started process 1576 to run task
[2025-04-04T08:46:10.681+0000] {standard_task_runner.py:87} INFO - Running: ['airflow', 'tasks', 'run', 'full_pipeline_dag', 'load_to_postgres', 'manual__2025-04-04T08:16:15.521213+00:00', '--job-id', '277', '--raw', '--subdir', 'DAGS_FOLDER/full_pipeline_dag.py', '--cfg-path', '/tmp/tmpikmt5li5']
[2025-04-04T08:46:10.684+0000] {standard_task_runner.py:88} INFO - Job 277: Subtask load_to_postgres
[2025-04-04T08:46:10.730+0000] {logging_mixin.py:188} WARNING - /home/airflow/.local/lib/python3.8/site-packages/airflow/settings.py:194 DeprecationWarning: The sql_alchemy_conn option in [core] has been moved to the sql_alchemy_conn option in [database] - the old setting has been used, but please update your config.
[2025-04-04T08:46:10.798+0000] {task_command.py:423} INFO - Running <TaskInstance: full_pipeline_dag.load_to_postgres manual__2025-04-04T08:16:15.521213+00:00 [running]> on host 43987fe3142a
[2025-04-04T08:46:10.962+0000] {taskinstance.py:2480} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='full_pipeline_dag' AIRFLOW_CTX_TASK_ID='load_to_postgres' AIRFLOW_CTX_EXECUTION_DATE='2025-04-04T08:16:15.521213+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-04-04T08:16:15.521213+00:00'
[2025-04-04T08:46:10.963+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-04-04T08:46:10.968+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', '\n        /opt/spark/bin/spark-submit         --master spark://spark-master:7077         /opt/spark-app/load_to_postgres.py\n        ']
[2025-04-04T08:46:10.974+0000] {subprocess.py:86} INFO - Output:
[2025-04-04T08:46:10.980+0000] {subprocess.py:93} INFO - /opt/spark/bin/load-spark-env.sh: line 68: ps: command not found
[2025-04-04T08:46:13.309+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SparkContext: Running Spark version 3.5.0
[2025-04-04T08:46:13.310+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SparkContext: OS info Linux, 5.15.167.4-microsoft-standard-WSL2, amd64
[2025-04-04T08:46:13.311+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SparkContext: Java version 17.0.14
[2025-04-04T08:46:13.361+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 WARN NativeCodeLoader: Unable to load native-hadoop library for your platform... using builtin-java classes where applicable
[2025-04-04T08:46:13.432+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO ResourceUtils: ==============================================================
[2025-04-04T08:46:13.433+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO ResourceUtils: No custom resources configured for spark.driver.
[2025-04-04T08:46:13.434+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO ResourceUtils: ==============================================================
[2025-04-04T08:46:13.434+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SparkContext: Submitted application: LoadCleanedToPostgres
[2025-04-04T08:46:13.449+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO ResourceProfile: Default ResourceProfile created, executor resources: Map(memory -> name: memory, amount: 1024, script: , vendor: , offHeap -> name: offHeap, amount: 0, script: , vendor: ), task resources: Map(cpus -> name: cpus, amount: 1.0)
[2025-04-04T08:46:13.455+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO ResourceProfile: Limiting resource is cpu
[2025-04-04T08:46:13.456+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO ResourceProfileManager: Added ResourceProfile id: 0
[2025-04-04T08:46:13.490+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SecurityManager: Changing view acls to: airflow
[2025-04-04T08:46:13.491+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SecurityManager: Changing modify acls to: airflow
[2025-04-04T08:46:13.492+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SecurityManager: Changing view acls groups to:
[2025-04-04T08:46:13.492+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SecurityManager: Changing modify acls groups to:
[2025-04-04T08:46:13.492+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SecurityManager: SecurityManager: authentication disabled; ui acls disabled; users with view permissions: airflow; groups with view permissions: EMPTY; users with modify permissions: airflow; groups with modify permissions: EMPTY
[2025-04-04T08:46:13.721+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO Utils: Successfully started service 'sparkDriver' on port 35521.
[2025-04-04T08:46:13.751+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SparkEnv: Registering MapOutputTracker
[2025-04-04T08:46:13.783+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SparkEnv: Registering BlockManagerMaster
[2025-04-04T08:46:13.805+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO BlockManagerMasterEndpoint: Using org.apache.spark.storage.DefaultTopologyMapper for getting topology information
[2025-04-04T08:46:13.806+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO BlockManagerMasterEndpoint: BlockManagerMasterEndpoint up
[2025-04-04T08:46:13.810+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SparkEnv: Registering BlockManagerMasterHeartbeat
[2025-04-04T08:46:13.839+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO DiskBlockManager: Created local directory at /tmp/blockmgr-cae07cf8-7873-4211-b65a-047091457d20
[2025-04-04T08:46:13.854+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO MemoryStore: MemoryStore started with capacity 434.4 MiB
[2025-04-04T08:46:13.876+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO SparkEnv: Registering OutputCommitCoordinator
[2025-04-04T08:46:13.989+0000] {subprocess.py:93} INFO - 25/04/04 08:46:13 INFO JettyUtils: Start Jetty 0.0.0.0:4040 for SparkUI
[2025-04-04T08:46:14.047+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO Utils: Successfully started service 'SparkUI' on port 4040.
[2025-04-04T08:46:14.192+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO StandaloneAppClient$ClientEndpoint: Connecting to master spark://spark-master:7077...
[2025-04-04T08:46:14.276+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO TransportClientFactory: Successfully created connection to spark-master/172.24.0.4:7077 after 50 ms (0 ms spent in bootstraps)
[2025-04-04T08:46:14.388+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO StandaloneSchedulerBackend: Connected to Spark cluster with app ID app-20250404084614-0006
[2025-04-04T08:46:14.410+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO StandaloneAppClient$ClientEndpoint: Executor added: app-20250404084614-0006/0 on worker-20250404081326-172.24.0.8-45963 (172.24.0.8:45963) with 2 core(s)
[2025-04-04T08:46:14.424+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO StandaloneSchedulerBackend: Granted executor ID app-20250404084614-0006/0 on hostPort 172.24.0.8:45963 with 2 core(s), 1024.0 MiB RAM
[2025-04-04T08:46:14.438+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO Utils: Successfully started service 'org.apache.spark.network.netty.NettyBlockTransferService' on port 40915.
[2025-04-04T08:46:14.440+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO NettyBlockTransferService: Server created on 43987fe3142a:40915
[2025-04-04T08:46:14.443+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO BlockManager: Using org.apache.spark.storage.RandomBlockReplicationPolicy for block replication policy
[2025-04-04T08:46:14.460+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO BlockManagerMaster: Registering BlockManager BlockManagerId(driver, 43987fe3142a, 40915, None)
[2025-04-04T08:46:14.465+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO BlockManagerMasterEndpoint: Registering block manager 43987fe3142a:40915 with 434.4 MiB RAM, BlockManagerId(driver, 43987fe3142a, 40915, None)
[2025-04-04T08:46:14.468+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO BlockManagerMaster: Registered BlockManager BlockManagerId(driver, 43987fe3142a, 40915, None)
[2025-04-04T08:46:14.470+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO BlockManager: Initialized BlockManager: BlockManagerId(driver, 43987fe3142a, 40915, None)
[2025-04-04T08:46:14.514+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO StandaloneAppClient$ClientEndpoint: Executor updated: app-20250404084614-0006/0 is now RUNNING
[2025-04-04T08:46:14.690+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO StandaloneSchedulerBackend: SchedulerBackend is ready for scheduling beginning after reached minRegisteredResourcesRatio: 0.0
[2025-04-04T08:46:14.857+0000] {subprocess.py:93} INFO - ðŸš€ SparkSession ready!
[2025-04-04T08:46:14.858+0000] {subprocess.py:93} INFO - ðŸ“¥ Loading cleaned data from MinIO...
[2025-04-04T08:46:14.919+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO SharedState: Setting hive.metastore.warehouse.dir ('null') to the value of spark.sql.warehouse.dir.
[2025-04-04T08:46:14.929+0000] {subprocess.py:93} INFO - 25/04/04 08:46:14 INFO SharedState: Warehouse path is 'file:/tmp/airflowtmpuc4825vb/spark-warehouse'.
[2025-04-04T08:46:15.699+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 WARN FileStreamSink: Assume no metadata directory. Error while looking for metadata directory in the path: s3a://nyc-taxi/clean/yellow_tripdata_2023-01-clean.parquet.
[2025-04-04T08:46:15.700+0000] {subprocess.py:93} INFO - java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-04-04T08:46:15.701+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-04-04T08:46:15.702+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-04-04T08:46:15.702+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-04-04T08:46:15.703+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-04-04T08:46:15.704+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-04-04T08:46:15.705+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-04-04T08:46:15.705+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-04-04T08:46:15.706+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-04-04T08:46:15.707+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.streaming.FileStreamSink$.hasMetadata(FileStreamSink.scala:53)
[2025-04-04T08:46:15.707+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:366)
[2025-04-04T08:46:15.708+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-04-04T08:46:15.709+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-04-04T08:46:15.709+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-04-04T08:46:15.710+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-04-04T08:46:15.711+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:563)
[2025-04-04T08:46:15.712+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-04-04T08:46:15.713+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-04-04T08:46:15.714+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-04-04T08:46:15.714+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-04-04T08:46:15.715+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-04-04T08:46:15.715+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-04-04T08:46:15.716+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-04-04T08:46:15.717+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-04-04T08:46:15.717+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-04-04T08:46:15.718+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-04-04T08:46:15.719+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-04-04T08:46:15.719+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-04T08:46:15.720+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-04-04T08:46:15.720+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-04-04T08:46:15.721+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-04-04T08:46:15.722+0000] {subprocess.py:93} INFO - 	... 26 more
[2025-04-04T08:46:15.803+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-04-04T08:46:15.803+0000] {subprocess.py:93} INFO -   File "/opt/spark-app/load_to_postgres.py", line 20, in <module>
[2025-04-04T08:46:15.806+0000] {subprocess.py:93} INFO -     df = spark.read.parquet(clean_path)
[2025-04-04T08:46:15.807+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/sql/readwriter.py", line 544, in parquet
[2025-04-04T08:46:15.807+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/java_gateway.py", line 1322, in __call__
[2025-04-04T08:46:15.808+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/pyspark.zip/pyspark/errors/exceptions/captured.py", line 179, in deco
[2025-04-04T08:46:15.808+0000] {subprocess.py:93} INFO -   File "/opt/spark/python/lib/py4j-0.10.9.7-src.zip/py4j/protocol.py", line 326, in get_return_value
[2025-04-04T08:46:15.809+0000] {subprocess.py:93} INFO - py4j.protocol.Py4JJavaError: An error occurred while calling o38.parquet.
[2025-04-04T08:46:15.810+0000] {subprocess.py:93} INFO - : java.lang.RuntimeException: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-04-04T08:46:15.810+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2688)
[2025-04-04T08:46:15.811+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.getFileSystemClass(FileSystem.java:3431)
[2025-04-04T08:46:15.812+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.createFileSystem(FileSystem.java:3466)
[2025-04-04T08:46:15.812+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.access$300(FileSystem.java:174)
[2025-04-04T08:46:15.813+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.getInternal(FileSystem.java:3574)
[2025-04-04T08:46:15.813+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem$Cache.get(FileSystem.java:3521)
[2025-04-04T08:46:15.814+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.FileSystem.get(FileSystem.java:540)
[2025-04-04T08:46:15.814+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.fs.Path.getFileSystem(Path.java:365)
[2025-04-04T08:46:15.815+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.$anonfun$checkAndGlobPathIfNecessary$1(DataSource.scala:724)
[2025-04-04T08:46:15.815+0000] {subprocess.py:93} INFO - 	at scala.collection.immutable.List.map(List.scala:293)
[2025-04-04T08:46:15.816+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource$.checkAndGlobPathIfNecessary(DataSource.scala:722)
[2025-04-04T08:46:15.816+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.checkAndGlobPathIfNecessary(DataSource.scala:551)
[2025-04-04T08:46:15.817+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.execution.datasources.DataSource.resolveRelation(DataSource.scala:404)
[2025-04-04T08:46:15.817+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.loadV1Source(DataFrameReader.scala:229)
[2025-04-04T08:46:15.818+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.$anonfun$load$2(DataFrameReader.scala:211)
[2025-04-04T08:46:15.819+0000] {subprocess.py:93} INFO - 	at scala.Option.getOrElse(Option.scala:189)
[2025-04-04T08:46:15.819+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.load(DataFrameReader.scala:211)
[2025-04-04T08:46:15.820+0000] {subprocess.py:93} INFO - 	at org.apache.spark.sql.DataFrameReader.parquet(DataFrameReader.scala:563)
[2025-04-04T08:46:15.820+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke0(Native Method)
[2025-04-04T08:46:15.821+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.NativeMethodAccessorImpl.invoke(NativeMethodAccessorImpl.java:77)
[2025-04-04T08:46:15.821+0000] {subprocess.py:93} INFO - 	at java.base/jdk.internal.reflect.DelegatingMethodAccessorImpl.invoke(DelegatingMethodAccessorImpl.java:43)
[2025-04-04T08:46:15.822+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.reflect.Method.invoke(Method.java:569)
[2025-04-04T08:46:15.822+0000] {subprocess.py:93} INFO - 	at py4j.reflection.MethodInvoker.invoke(MethodInvoker.java:244)
[2025-04-04T08:46:15.822+0000] {subprocess.py:93} INFO - 	at py4j.reflection.ReflectionEngine.invoke(ReflectionEngine.java:374)
[2025-04-04T08:46:15.823+0000] {subprocess.py:93} INFO - 	at py4j.Gateway.invoke(Gateway.java:282)
[2025-04-04T08:46:15.823+0000] {subprocess.py:93} INFO - 	at py4j.commands.AbstractCommand.invokeMethod(AbstractCommand.java:132)
[2025-04-04T08:46:15.823+0000] {subprocess.py:93} INFO - 	at py4j.commands.CallCommand.execute(CallCommand.java:79)
[2025-04-04T08:46:15.824+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.waitForCommands(ClientServerConnection.java:182)
[2025-04-04T08:46:15.825+0000] {subprocess.py:93} INFO - 	at py4j.ClientServerConnection.run(ClientServerConnection.java:106)
[2025-04-04T08:46:15.825+0000] {subprocess.py:93} INFO - 	at java.base/java.lang.Thread.run(Thread.java:840)
[2025-04-04T08:46:15.825+0000] {subprocess.py:93} INFO - Caused by: java.lang.ClassNotFoundException: Class org.apache.hadoop.fs.s3a.S3AFileSystem not found
[2025-04-04T08:46:15.826+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClassByName(Configuration.java:2592)
[2025-04-04T08:46:15.826+0000] {subprocess.py:93} INFO - 	at org.apache.hadoop.conf.Configuration.getClass(Configuration.java:2686)
[2025-04-04T08:46:15.827+0000] {subprocess.py:93} INFO - 	... 29 more
[2025-04-04T08:46:15.827+0000] {subprocess.py:93} INFO - 
[2025-04-04T08:46:15.856+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO SparkContext: Invoking stop() from shutdown hook
[2025-04-04T08:46:15.857+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO SparkContext: SparkContext is stopping with exitCode 0.
[2025-04-04T08:46:15.872+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO SparkUI: Stopped Spark web UI at http://43987fe3142a:4040
[2025-04-04T08:46:15.876+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO StandaloneSchedulerBackend: Shutting down all executors
[2025-04-04T08:46:15.882+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO StandaloneSchedulerBackend$StandaloneDriverEndpoint: Asking each executor to shut down
[2025-04-04T08:46:15.901+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO MapOutputTrackerMasterEndpoint: MapOutputTrackerMasterEndpoint stopped!
[2025-04-04T08:46:15.920+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO MemoryStore: MemoryStore cleared
[2025-04-04T08:46:15.921+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO BlockManager: BlockManager stopped
[2025-04-04T08:46:15.926+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO BlockManagerMaster: BlockManagerMaster stopped
[2025-04-04T08:46:15.928+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO OutputCommitCoordinator$OutputCommitCoordinatorEndpoint: OutputCommitCoordinator stopped!
[2025-04-04T08:46:15.940+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO SparkContext: Successfully stopped SparkContext
[2025-04-04T08:46:15.941+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO ShutdownHookManager: Shutdown hook called
[2025-04-04T08:46:15.942+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-73254adc-888b-4b8d-82bb-9e392c02bd35
[2025-04-04T08:46:15.948+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-959b8ad7-fd9b-4739-b8c5-553f6613738f
[2025-04-04T08:46:15.952+0000] {subprocess.py:93} INFO - 25/04/04 08:46:15 INFO ShutdownHookManager: Deleting directory /tmp/spark-73254adc-888b-4b8d-82bb-9e392c02bd35/pyspark-555f69af-3b60-4ebf-9b1c-b955c1af0fba
[2025-04-04T08:46:15.979+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-04-04T08:46:15.999+0000] {taskinstance.py:2698} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/models/taskinstance.py", line 433, in _execute_task
    result = execute_callable(context=context, **execute_callable_kwargs)
  File "/home/airflow/.local/lib/python3.8/site-packages/airflow/operators/bash.py", line 212, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-04-04T08:46:16.013+0000] {taskinstance.py:1138} INFO - Marking task as FAILED. dag_id=full_pipeline_dag, task_id=load_to_postgres, execution_date=20250404T081615, start_date=20250404T084610, end_date=20250404T084616
[2025-04-04T08:46:16.077+0000] {standard_task_runner.py:107} ERROR - Failed to execute job 277 for task load_to_postgres (Bash command failed. The command returned a non-zero exit code 1.; 1576)
[2025-04-04T08:46:16.116+0000] {local_task_job_runner.py:234} INFO - Task exited with return code 1
[2025-04-04T08:46:16.160+0000] {taskinstance.py:3280} INFO - 0 downstream tasks scheduled from follow-on schedule check
